<a href="https://colab.research.google.com/github/hananlu/aiBigData/blob/master/Week_3_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Data Cleaning (Filling missing value)

In [2]:
data = {
    "umur": [25, 30, None, 28],
    "pendapatan": [3000, 4000, 3500, None]
}

df = pd.DataFrame(data)

df.head()

   umur  pendapatan
0  25.0      3000.0
1  30.0      4000.0
2   NaN      3500.0
3  28.0         NaN

### Delete Dupilcated

In [3]:
data = {
    "nama": ["A", "B", "B", "C"],
    "umur": [20, 25, 25, 30]
}

df = pd.DataFrame(data)

df.head()

  nama  umur
0    A    20
1    B    25
2    B    25
3    C    30

### Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler

data = {
    "pendapatan": [3000, 5000, 7000, 9000]
}

df = pd.DataFrame(data)

### Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler

data = {
    "umur": [20, 25, 30, 35],
    "pendapatan": [3000, 5000, 7000, 9000]
}

df = pd.DataFrame(data)

### Data Encoding

In [4]:
data = {
    "gender": ["Male", "Female", "Female", "Male"]
}

df = pd.DataFrame(data)

### Feature Engineering

In [ ]:
data = {
    "tanggal": ["2024-01-01", "2024-02-05", "2024-03-10"]
}

df = pd.DataFrame(data)

df["tanggal"] = pd.to_datetime(df["tanggal"])

df["bulan"] = df["tanggal"].dt.month

df["hari"] = df["tanggal"].dt.day